#!/usr/bin/env python3
"""Validate XDS SVG assets and generate the Vue icon registry."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from xml.etree import ElementTree


ROOT = Path(__file__).resolve().parents[1]
ICON_DIR = ROOT / "assets" / "icons"
MAP_FILE = ROOT / "references" / "components" / "icons-map.md"
OUTPUT = ROOT / "ui" / "components" / "iconRegistry.generated.js"
SVG_NAMESPACE = "http://www.w3.org/2000/svg"
ALLOWED_TAGS = {"path", "circle", "ellipse", "line", "polyline", "polygon", "rect", "g"}


def local_name(value: str) -> str:
    return value.rsplit("}", 1)[-1]


def node_to_data(element: ElementTree.Element) -> dict:
    tag = local_name(element.tag)
    if tag not in ALLOWED_TAGS:
        raise ValueError(f"unsupported SVG element <{tag}>")
    return {
        "tag": tag,
        "attrs": {local_name(key): value for key, value in sorted(element.attrib.items())},
        "children": [node_to_data(child) for child in element],
    }


def validate_root(path: Path, root: ElementTree.Element) -> None:
    if local_name(root.tag) != "svg":
        raise ValueError("root element must be <svg>")
    if root.tag.startswith("{") and not root.tag.startswith(f"{{{SVG_NAMESPACE}}}"):
        raise ValueError("unexpected SVG namespace")
    if root.attrib.get("viewBox") != "0 0 24 24":
        raise ValueError('viewBox must be "0 0 24 24"')
    if root.attrib.get("width") != "24" or root.attrib.get("height") != "24":
        raise ValueError('width and height must both be "24"')
    if not list(root):
        raise ValueError("icon has no vector children")
    if not path.stem.endswith("-filled"):
        expected = {
            "fill": "none",
            "stroke": "currentColor",
            "stroke-width": "1.5",
            "stroke-linecap": "round",
            "stroke-linejoin": "round",
        }
        for key, value in expected.items():
            if root.attrib.get(key) != value:
                raise ValueError(f'{key} must be "{value}"')
    else:
        serialized = ElementTree.tostring(root, encoding="unicode")
        if "currentColor" not in serialized:
            raise ValueError("filled icon must use currentColor")


def load_icons() -> dict[str, dict]:
    icons: dict[str, dict] = {}
    errors: list[str] = []
    for path in sorted(ICON_DIR.glob("*.svg")):
        try:
            root = ElementTree.parse(path).getroot()
            validate_root(path, root)
            root_attrs = {
                local_name(key): value
                for key, value in sorted(root.attrib.items())
                if local_name(key) not in {"width", "height", "viewBox"}
            }
            icons[path.stem] = {
                "attrs": root_attrs,
                "nodes": [node_to_data(child) for child in root],
            }
        except (ElementTree.ParseError, ValueError) as error:
            errors.append(f"{path.relative_to(ROOT)}: {error}")
    if errors:
        raise ValueError("\n".join(errors))
    return icons


def render_registry(icons: dict[str, dict]) -> str:
    payload = json.dumps(icons, ensure_ascii=True, indent=2, separators=(",", ": "))
    return (
        "// Generated by scripts/build-icon-registry.py. Do not edit by hand.\n"
        f"export const ICON_REGISTRY = Object.freeze({payload})\n\n"
        "export const ICON_NAMES = Object.freeze(Object.keys(ICON_REGISTRY))\n\n"
        "export function normalizeIconName(name) {\n"
        "  return String(name || '').trim().replace(/\\.svg$/i, '')\n"
        "}\n\n"
        "export function hasIcon(name) {\n"
        "  return Object.prototype.hasOwnProperty.call(ICON_REGISTRY, normalizeIconName(name))\n"
        "}\n"
    )


def validate_map(icons: dict[str, dict]) -> None:
    body = MAP_FILE.read_text(encoding="utf-8")
    missing = [name for name in icons if f"`{name}.svg`" not in body]
    if missing:
        raise ValueError(
            f"{MAP_FILE.relative_to(ROOT)} does not mention: " + ", ".join(missing)
        )


def validate_component_usage() -> None:
    allowed_inline_svg = {
        "XCheckbox.vue": 2,  # control-state glyphs, not library icons
        "XEmptyState.vue": 1,  # empty-state illustration
        "XHeaderBar.vue": 1,  # official nine-dot Platform app switcher
        "XIcon.vue": 1,  # canonical renderer
        "XSpinner.vue": 1,  # progress indicator
    }
    errors: list[str] = []
    # rglob để quét cả thư mục con (vd ui/templates/mobile/) — trước đây chỉ glob 1 cấp
    # nên các template mobile lọt lưới kiểm tra kích thước icon.
    sources = sorted((ROOT / "ui" / "components").rglob("*.vue"))
    sources += sorted((ROOT / "ui" / "templates").rglob("*.vue"))
    size_pattern = re.compile(r':size="(\d+)"')
    allowed_sizes = {12, 16, 20, 24, 28, 32, 36, 40, 44, 48}

    for path in sources:
        body = path.read_text(encoding="utf-8")
        svg_count = body.count("<svg")
        expected = allowed_inline_svg.get(path.name, 0)
        if svg_count != expected:
            errors.append(
                f"{path.relative_to(ROOT)} has {svg_count} inline SVG(s); expected {expected}"
            )
        if "ICON_PATHS" in body or "iconPaths(" in body:
            errors.append(f"{path.relative_to(ROOT)} contains a duplicated icon path map")
        invalid_sizes = sorted(
            {int(value) for value in size_pattern.findall(body)} - allowed_sizes
        )
        if invalid_sizes:
            errors.append(
                f"{path.relative_to(ROOT)} uses non-XDS XIcon sizes: {invalid_sizes}"
            )

    if errors:
        raise ValueError("\n".join(errors))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate assets and fail if the generated registry is stale",
    )
    args = parser.parse_args()

    try:
        icons = load_icons()
        validate_map(icons)
        validate_component_usage()
    except ValueError as error:
        print(error, file=sys.stderr)
        return 1

    generated = render_registry(icons)
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            print(
                "icon registry is stale; run scripts/build-icon-registry.py",
                file=sys.stderr,
            )
            return 1
    else:
        OUTPUT.write_text(generated, encoding="utf-8")

    filled = sum(name.endswith("-filled") for name in icons)
    mode = "checked" if args.check else "generated"
    print(f"{mode} {len(icons)} XDS icons ({filled} filled)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
